
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 26 04:39:38 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 51;
  public static final int CONT = 4;
  public static final int PLUSPLUS = 36;
  public static final int CONST = 7;
  public static final int LBRCK = 42;
  public static final int NOT_EQUAL = 29;
  public static final int LPAREN = 40;
  public static final int MINUS = 23;
  public static final int RPAREN = 41;
  public static final int SEMICOLON = 38;
  public static final int AND = 34;
  public static final int RECORD = 16;
  public static final int LS = 32;
  public static final int OR = 35;
  public static final int COMMA = 39;
  public static final int CLASS = 8;
  public static final int LSE = 33;
  public static final int DIV = 25;
  public static final int EXT = 21;
  public static final int PLUS = 22;
  public static final int ASSIGN = 27;
  public static final int IF = 5;
  public static final int THIS = 20;
  public static final int DOT = 47;
  public static final int EOF = 0;
  public static final int RBRCK = 43;
  public static final int MINUSMINUS = 37;
  public static final int RETURN = 15;
  public static final int EQUAL = 28;
  public static final int SUPER = 18;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int IDENT = 49;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int GTE = 31;
  public static final int DBLDOT = 46;
  public static final int LBRACE = 44;
  public static final int ELSE = 6;
  public static final int ENUM = 17;
  public static final int READ = 13;
  public static final int GOTO = 19;
  public static final int WHILE = 10;
  public static final int RBRACE = 45;
  public static final int PROG = 2;
  public static final int THREEDOTS = 48;
  public static final int BOOL_CONST = 50;
  public static final int GT = 30;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int NUMBER_CONST = 52;
  public static final int PCT = 26;
}

